### ISSUE TITLE
Faspex5 Multiple Matching contact for distribution list

### ISSUE THREAD

**Issue by Gerardo-Parker** [IBM/aspera-cli#120]
Using faspex5 package send 

if a distribution list contains the same email in a distribution list the package sends to fail. 
example:

```json
{"recipients":["email1@google.com", "distributionlistwithemail1@google.com"]}
```

Is there an option that can be provided to the package info payload to ignore duplicate emails. I work with several 3rd party companies and occasionally their distribution lists overlap across teams.

**Comment by laurent-martin** [comment]
If names are specified as a list, then a lookup is performed on all recipient types.
lookup is case insensitive and based on substring.
(This will be fixed in the next version, where it will be an exact match).

The workaround in 4.13 and - is to specify that's it's the exact name:

```json
{"recipients":[{"name":"email1@google.com"},{"name":"distributionlistwithemail1@google.com"}]}
```

You can also set the type of user:

- user
- workgroup
- external_user
- distribution_list
- shared_inbox)

e.g. if both are registered users, then :

```json
{"recipients":[{"type":"user","name":"email1@google.com"},{"type":"user","name":"distributionlistwithemail1@google.com"}]}
```

refer to Faspex 5 api:
https://developer.ibm.com/apis/catalog/aspera--ibm-aspera-faspex-5-0-api/api/API--aspera--ibm-aspera-faspex-api#createPackageRecord

Beta of next version , if you want to test (`gem install` ...):

https://ibm.biz/aspera-cli-beta

And doc for next version:

https://github.com/IBM/aspera-cli/tree/develop#faspex-5-send-a-package

**Comment by Gerardo-Parker** [comment]
I updated from 4.12.0 to 4.13.0 and tried updating the payload to use [{"name": "email"}], I was still running into some issues with sending the package with a distro list still marking as invalid parameter but got around the issue by forcing the type to external_user.

**Comment by laurent-martin** [comment]
Thanks for the feedback.
