### ISSUE TITLE
"Permission denied" while receiving faspex5 package inside Singularity container.  v4.13

### ISSUE THREAD

**Issue by ggaffield** [IBM/aspera-cli#121]
I created a singularity container from your Docker image like this:
`singularity build ascli_ORIG.sif docker://martinlaurent/ascli`

Ran it like this:
`singularity shell ascli_ORIG.sif`

```console
Singularity> ascli faspex5 packages rec 146 --url=https://transfer.xyz.org/aspera/faspex --auth=jwt --username=Glenn.Gaffield@xyz.org --private_key=@val:@file:"$HOME/.ssh/id_rsa" --client_id=[snip] --client_secret=[snip]
Receiving package 146
I/O error : Permission denied
I/O error : Permission denied
I/O error : Permission denied
I/O error : Permission denied
I/O error : Permission denied
I/O error : Permission denied
ascp: Permission denied, exiting.
E, [2023-09-14T16:38:14.727346 #217265] ERROR -- : code: 29
W, [2023-09-14T16:38:14.730109 #217265]  WARN -- : An error occurred: Permission denied
W, [2023-09-14T16:38:14.730232 #217265]  WARN -- : resuming in  2 seconds (retry left:6)
I/O error : Permission denied
I/O error : Permission denied
I/O error : Permission denied
I/O error : Permission denied
I/O error : Permission denied
I/O error : Permission denied
ascp: Permission denied, exiting.
E, [2023-09-14T16:38:17.742100 #217265] ERROR -- : code: 29
W, [2023-09-14T16:38:17.743364 #217265]  WARN -- : An error occurred: Permission denied
E, [2023-09-14T16:38:17.743523 #217265] ERROR -- : non-retryable error
ERROR: FASP(ascp): Permission denied
```

Who am I?
```
Singularity> id
uid=63660(gaffield) gid=10000(xyzuser) groups=10000(xyzuser)
```

strace showed the following:
```
openat(AT_FDCWD, "/home/cliuser/.aspera/sdk/aspera.conf", O_RDONLY) = -1 EACCES (Permission denied)
openat(AT_FDCWD, "/home/cliuser/.aspera/sdk/aspera-license", O_RDONLY) = -1 EACCES (Permission denied)
```

```
Singularity> ls -l /home/cliuser/.aspera/sdk/
total 41913
-rwxr-xr-x 1 cliuser cliuser 10546736 Jun 30 03:34 ascp
-rwxr-xr-x 1 cliuser cliuser 10068040 Jun 30 03:34 ascp4
-rw------- 1 cliuser cliuser     1460 Jun 30 03:34 aspera-license
-rw------- 1 cliuser cliuser      236 Jun 30 03:34 aspera.conf
-rw------- 1 cliuser cliuser      668 Jun 30 03:34 aspera_bypass_dsa.pem
-rw------- 1 cliuser cliuser     3243 Jun 30 03:34 aspera_bypass_rsa.pem
-rw------- 1 cliuser cliuser      989 Jun 30 03:34 aspera_fallback_cert.pem
-rw------- 1 cliuser cliuser      887 Jun 30 03:34 aspera_fallback_key.pem
-rwxr-xr-x 1 cliuser cliuser 17090653 Jun 30 03:34 asperatransferd
drwxr-xr-x 2 cliuser cliuser       68 Jun 30 03:34 lib
-rw-r--r-- 1 cliuser cliuser  5202104 Jun 30 03:34 libafwsfeed.so
-rw-r--r-- 1 cliuser cliuser       73 Jun 30 03:34 product-info.mf
```
To work around this problem, I built a new container in sandbox mode.  Because files inside the container are immutable otherwise. 
 I altered the permissions of the 6 files with 0600 permissions to 0644, then converted the sandbox container to a standard container.
  
Perhaps you could change the permissions in future Docker images, if it doesn't break security best practices.

**Comment by laurent-martin** [comment]
Thanks for your valuable comments, I'll have a look .

Notice this:
https://github.com/IBM/aspera-cli#details-on-the-container

Typically:

the folder /home/cliuser/.aspera should be a volume (mount) to the host to the calling user's $HOME/.aspera because it contains created files during runtime, like the config file, and other cache files.

Also, by default in non-container version, the SDK is installed in: $HOME/.aspera/ascli/sdk, but the container overrides that with an env var so that it's located at: /home/cliuser/.aspera/sdk : probably a next version will have that in standard in non-container version.

The issue you exhibit is probably something else, I'll check and let you know.

Also, the container is currently published under my name, but it might be published by IBM in the future.

I am also testing a single-exec version of ascli:

https://eudemo.asperademo.com/download/ascli.Darwin-arm64

https://eudemo.asperademo.com/download/ascli.Linux-x86_64

**Comment by laurent-martin** [comment]
If you can, try that beta:
docker://martinlaurent/ascli:4.14.0.pre

**Comment by ggaffield** [comment]
I tried docker://martinlaurent/ascli:4.14.0
Problem resolved.
Thanks a lot!
