### ISSUE TITLE
aoc packages list - exclude_dropbox_packages query option is ignored

### ISSUE THREAD

**Issue by sethleblanc** [IBM/aspera-cli#135]
Hello,

Using the command `ascli aoc packages list --query=@json:'{"exclude_dropbox_packages":false}'` does not return packages in dropboxes. Using --log-level=debug, I can see that the exclude_dropbox_packages option has been changed to true when calling the API:
`D, [2024-02-16T12:31:57.299410 #28828] DEBUG -- : URI=https://api.ibmaspera.com/api/v1/packages?archived=false&has_content=true&received=true&completed=true&exclude_dropbox_packages=true&workspace_id=1234&per_page=1000&page=1`

It does work when specifying a dropbox_id (i.e. `--query=@json:'{"dropbox_id":"1234","exclude_dropbox_packages":false}'`). However, this obviously only returns the packages in that single dropbox. Leaving out the dropbox_id used to return a list of packages in _all_ dropboxes that the user has access to. This broke in version 4.16.0.

Cheers,
Seth

**Comment by laurent-martin** [comment]
I will have a look at that next week.
Meanwhile, you can revert to 4.15

**Comment by laurent-martin** [comment]
Should be fixed in beta:
[Link to Beta](https://ibm.biz/aspera-cli-beta)
there, by default `exclude_dropbox_packages` is set to `true` for listing normal packages, and set to `false` if either `dropbox_id` or `dropbox_name` is provided in query.
If `exclude_dropbox_packages` is provided in query, it is not overriden.

**Comment by sethleblanc** [comment]
Confirmed working in the beta, thanks for the quick fix!
