### ISSUE TITLE
Publish documentation to rubydoc.info

### ISSUE THREAD

**Issue by gegles** [IBM/aspera-cli#15]
Something is not working and the documentation is not making it to https://www.rubydoc.info/gems/aspera-cli/4.0.0.pre1

**Comment by gegles** [comment]
@laurent-martin seem to think this is a limitation of the rubydoc system and that only full versions `4.0.0` get the doc published.

For example https://rubygems.org/gems/factory_girl/versions/4.0.0.rc1 does not have a doc either.

**Comment by laurent-martin** [comment]
The documentation probably does not generate due to non digital version number. probably a bug in rubydoc ?
see: https://rubygems.org/gems/factory_girl/versions/4.0.0.rc1
digit version => doc, non dit -> no doc


Also:
one can add a li nk to source code using metadata field “source_code_uri” in aspera-cli.gemspec

see https://guides.rubygems.org/specification-reference/#metadata

**Comment by gegles** [comment]
According to @laurent-martin this should "just work" once we do a proper (non `pre`) release. Let's wait and hope. 🤞🏻
