### ISSUE TITLE
ascp command can not continue with -k 1 after transferring break

### ISSUE THREAD

**Issue by Zefeng-Wu** [IBM/aspera-cli#54]
Ascp command on Linux system can not continue with -k 1 after transferring break.  If I rerun the command, ascp will always re-download. How can I continue downloading using the temporary file? (.aspera-ckpt).  My command is as follows.
`ascp -QT -k 1 -l 500m -P 33001 -i ~/.aspera/connect/etc/asperaweb_id_dsa.openssh era-fasp@fasp.sra.ebi.ac.uk:/vol1/srr/SRR874/003/SRR8742453 0sra/SRR8742453`

**Comment by laurent-martin** [comment]
Hi,
This repo is about `ascli` not `ascp`. Although `ascli` uses `ascp` under the cover. So you are not in the right place to ask this.

The equivalent of `-k 1` in `ascli` is `--ts=@json:'{"resume_policy":"attrs"}'`

`ascp` does not automatically resume a transfer, the user has to re-execute the command and have option `-k` different from `0`.

`ascli` does resume automatically when using agent `direct` (i.e. local `ascp`) through a configurable scheme (for "retryable" errors).

if `-k 1` is provided, resume shall be activated (it checks files attributes).

note that the `.aspera-ckpt` file (or `.aspx` depending on `aspera.conf`) is not a temp file, but it is a "checkpoint" file, it is typically 64 to 80 bytes and contains information like attribute/checksum to allow resume.

advice:
* try `-k2` instead of `-k1`
* add `-DDL-` that will display debug info
