### ISSUE TITLE
Question: command line limit?

### ISSUE THREAD

**Issue by anyasb** [IBM/aspera-cli#71]
Hi!
Question:  are you aware of any character limits within CLI?

The use case is transferring packages via CLI to am Aspera on Cloud instance.   They want to use filenames that may be 100+ characters long. 

Thanks!
+a+

**Comment by laurent-martin** [comment]
There are no hardcoded command line length limit in `ascli` itself. The command line length is only potentially limited by the underlying shell (bash, cmd, etc...)

Using `ascli` as an integration tool is not the best programmatic way. When possible it is best to use the Transfer SDK. Nevertheless, it is recognized that it can be very convenient to use `ascli`, as no coding is required, while the use of the transfer SDK requires some minimum coding.

For list of files to transfer, yes, it is possible to provide them on the command line:

The options to provide the list of files to transfer is described here:
<https://github.com/IBM/aspera-cli#list-of-files-for-transfers>

Bascally, `ascli` expects the list of files to be provided as an "extended value" of type "Array" . This list (Array) is read depending on the option `sources` (`--sources`): by default the value is `@args` which means it is read from the command line.  (remaining command line parameters are taken as the list of files).

If `ascli` is used programmatically, with file lists generated by a program, then the best approach is that a "file list" is generated in a text file with one line per file (file pair list is also supported).

For example, if the list of files to send is placed (one per line, separated by "\n") in a file named `/tmp/myfilelist.txt`, then sending the files can be using option: `--sources=@lines:@file:/tmp/myfilelist.txt`

* `@file:` means that the file specified on the right is read, and the content provided to the left
* `@lines` means that the value coming from the right is cut with separator "\n" , forming an extended value of type "Array"
* `--sources` is the option that expects the extended value containing the list of files as value, precisely the result of `@lines`

Also note the following: When using the `direct` agent (i.e. `ascp` locally), the list of file coming from command line (or file if @lines:@file: is used) does anyway generate "file list" in a temporary file, and this file is provided to `ascp` using `--file-list`, so there is no limit in number of files here either due to `ascp` command line length, as anyway files are not provided on ascp command line.
